obstacle_range: 2
raytrace_range: 10
#robot_radius: ir_of_robot
inflation_radius: 0.2
# obstacles_layer:
#   obstacle_keep_time: 0.5 
#   observation_sources: point_cloud_sensor
#   point_cloud_sensor: {sensor_frame: body, data_type: PointCloud2, topic: /detector/obstacle, marking: true, clearing: true}