global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  always_send_full_costmap: true
  publish_frequency: 5.0
  static_map: false
  inflation_radius: 0.2
  rolling_window: false
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: prohibition_layer, type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}
  obstacle_layer:
    enabled: true
    observation_sources: obstacle_cloud ground_cloud
    track_unknown_space: true
    expected_update_rate: 10.0  
    max_obstacle_height: 1
    min_obstacle_height: -1
    obstacle_cloud:
      observation_persistence: 1.5  
      sensor_frame: body  
      data_type: PointCloud2
      topic: /detector/obstacle 
      marking: true
      clearing: false
    ground_cloud:
      sensor_frame: body  
      data_type: PointCloud2
      topic: /cloud_registered_body 
      marking: false
      clearing: true
  prohibition_layer:
    enabled: false
    fill_polygons: true
    prohibition_areas:
      - [[2.3, -1.0], [2.3, 1.0],[2.2, 1.0], [2.2, -1.0]]    # 垂直线段，x=1.5, y从2.0到3.0#
